export const LOGIN_REQUEST = "@account/login-request"
export const LOGIN_SUCCESS = "@account/login-success"
export const LOGIN_FAILURE = "@account/login-failure"
export const SILENT_LOGIN = "@account/silent-login"
export const LOGOUT = "@account/logout"
export const REGISTER = "@account/register"
export const UPDATE_PROFILE = "@account/update-profile"
